version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: usovix/productapp:latest
    build: .
    container_name: productapp-backend
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/productdb

volumes:
  mongo-data: